language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.0
    - android-21
    - extra-android-support
    - extra-android-m2repository
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
